collections:
  datascience:
    output: true
    permalink: /datascience/:path/
  setup:
    output: true
    permalink: /setup/:path/
  info:
    output: true
    permalink: /info/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

url: "https://lonedune.github.io"
baseurl: /pages
